/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteCoastRouteImport } from './routes/_site/coast'
import { Route as SiteInquireRouteImport } from './routes/_site/inquire'
import { Route as SiteTableRouteImport } from './routes/_site/table'
import { Route as SiteStayIndexRouteImport } from './routes/_site/stay.index'
import { Route as SiteStaySlugRouteImport } from './routes/_site/stay.$slug'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCoastRoute = SiteCoastRouteImport.update({
  id: '/coast',
  path: '/coast',
  getParentRoute: () => SiteRoute,
} as any)
const SiteInquireRoute = SiteInquireRouteImport.update({
  id: '/inquire',
  path: '/inquire',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTableRoute = SiteTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStayIndexRoute = SiteStayIndexRouteImport.update({
  id: '/stay/',
  path: '/stay/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStaySlugRoute = SiteStaySlugRouteImport.update({
  id: '/stay/$slug',
  path: '/stay/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/coast': typeof SiteCoastRoute
  '/inquire': typeof SiteInquireRoute
  '/table': typeof SiteTableRoute
  '/stay/$slug': typeof SiteStaySlugRoute
  '/stay/': typeof SiteStayIndexRoute
}
export interface FileRoutesByTo {
  '/coast': typeof SiteCoastRoute
  '/inquire': typeof SiteInquireRoute
  '/table': typeof SiteTableRoute
  '/': typeof SiteIndexRoute
  '/stay/$slug': typeof SiteStaySlugRoute
  '/stay': typeof SiteStayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/coast': typeof SiteCoastRoute
  '/_site/inquire': typeof SiteInquireRoute
  '/_site/table': typeof SiteTableRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/stay/$slug': typeof SiteStaySlugRoute
  '/_site/stay/': typeof SiteStayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coast' | '/inquire' | '/table' | '/stay/$slug' | '/stay/'
  fileRoutesByTo: FileRoutesByTo
  to: '/coast' | '/inquire' | '/table' | '/' | '/stay/$slug' | '/stay'
  id:
    | '__root__'
    | '/_site'
    | '/_site/coast'
    | '/_site/inquire'
    | '/_site/table'
    | '/_site/'
    | '/_site/stay/$slug'
    | '/_site/stay/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/coast': {
      id: '/_site/coast'
      path: '/coast'
      fullPath: '/coast'
      preLoaderRoute: typeof SiteCoastRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/inquire': {
      id: '/_site/inquire'
      path: '/inquire'
      fullPath: '/inquire'
      preLoaderRoute: typeof SiteInquireRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/table': {
      id: '/_site/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof SiteTableRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/stay/': {
      id: '/_site/stay/'
      path: '/stay'
      fullPath: '/stay/'
      preLoaderRoute: typeof SiteStayIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/stay/$slug': {
      id: '/_site/stay/$slug'
      path: '/stay/$slug'
      fullPath: '/stay/$slug'
      preLoaderRoute: typeof SiteStaySlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteCoastRoute: typeof SiteCoastRoute
  SiteInquireRoute: typeof SiteInquireRoute
  SiteTableRoute: typeof SiteTableRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteStaySlugRoute: typeof SiteStaySlugRoute
  SiteStayIndexRoute: typeof SiteStayIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteCoastRoute: SiteCoastRoute,
  SiteInquireRoute: SiteInquireRoute,
  SiteTableRoute: SiteTableRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteStaySlugRoute: SiteStaySlugRoute,
  SiteStayIndexRoute: SiteStayIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
